### ISSUE TITLE
Chapter 6 not working

### ISSUE THREAD

**Issue by arteniioleg** [neuronalmotion/Mastering-Qt-5#7]
![screenshot from 2017-08-27 10-47-56](https://user-images.githubusercontent.com/28860670/29748029-5949ead4-8b15-11e7-8ffd-8d91389d8bbb.png)

https://github.com/neuronalmotion/Mastering-Qt-5/blob/920a2690d938494005a5ce4265c7f1abfa049cad/Chapter_06/factory.js#L31-L32

**Comment by arteniioleg** [comment]
I added right before that code

```js
if (component.status !== 1) {
    console.debug("Error: "+ component.errorString());
}
```

and it showed

```
qml: Error: Apple.qml:25 Invalid property assignment: unsupported type "Qt3DRender::QAbstractTexture*"
```

https://github.com/neuronalmotion/Mastering-Qt-5/blob/920a2690d938494005a5ce4265c7f1abfa049cad/Chapter_06/Apple.qml#L24-L27

https://bugreports.qt.io/browse/QT3DS-1

**Comment by arteniioleg** [comment]
After commenting `//diffuse: ...` it started working but it doesn't look like the screenshot in the book

![staticshot_27-08-2017_11-18-33](https://user-images.githubusercontent.com/28860670/29748161-7ef3c5d0-8b19-11e7-8574-f49fc3e9f16c.png)

**Comment by arteniioleg** [comment]
_P.S. My investigation ends here, I will move on to the next chapter._

**Comment by GuillaumeLazar** [comment]
Thanks _arteniioleg_ for your great investigation. Your link (https://bugreports.qt.io/browse/QT3DS-1) is interesting. It seems that something is broken about the diffuse texture of Qt3D in recent Qt versions.

Even if Qt argue that Qt3D is ready for the realease state, a long way will be required to have a stable module.

Have fun with OpenCV concerning the next chapter!

**Comment by GuillaumeLazar** [comment]
I created an errata section based on your investigation: https://github.com/neuronalmotion/Mastering-Qt-5#chapter-6

I close the issue for now.

**Comment by arteniioleg** [comment]
Thanks.

Maybe you should comment on https://bugreports.qt.io/browse/QT3DS-1 to speed up the fix.

**Comment by craigusr** [comment]
Hello, You can get the DiffuseMapMaterial to work in Apple.qml using the following code.

    DiffuseMapMaterial {
        id: material
        diffuse: TextureLoader {
        source: "qrc:/models/apple-texture.png"
        }
    }
